### PR TITLE
fix to getClosestJointPose

### PR DESCRIPTION
**Pull request by jrgnicho**
When IK for the closest pose fails then the search for the closest pose is done in joint space

### CODE REVIEW

**Comment by shaun-edwards** [comment]
This change could significant increase the complexity of the method call.  I agree with the rational in #86, but can we come up with a less complex implementation?  Also, this mixes distance metrics.  First cartesian distance is used, then joint distance is used.

**Comment by jrgnicho** [comment]
An alternative would be to buffer up the poses in an array order by cartesian distance, in that case if IK fails on the closest then the next closest could be tested for IK and so on.  This approach would avoid mixing distance metrics but it would not guarantee a result.

**Comment by jrgnicho** [comment]
While I agree that the complexity will increase when the search in cartesian space fails, in my testing of this change in the amos project it rarely resorted to a joint search between points that were very close.  I don't think that mixing distance metrics here is necessarily detrimental.

**Comment by shaun-edwards** [comment]
+1

**Pull request merged**
