### PR TITLE
Planning graph optimization

### PR DESCRIPTION
**Pull request by psturgeon**
Completed initial version of add/modify/remove and small clean-up within the graph construction and solving.

### CODE REVIEW

**Comment by psturgeon** [comment]
@jrgnicho  , this has the latest add/modify/delete that can be tested

**Comment by shaun-edwards** [comment]
@psturgeon, it appears that the latest changes from `ros-industrial-consortium:hydro-devel` have not been pulled into your branch.  It's causing some wierd diffs and can't be merged automatically.

**Comment by jrgnicho** [comment]
Great, I'll test the add/modify/remove functionality and provide my feedback here

**Comment by psturgeon** [comment]
@shaun-edwards This PR should be re-merged with latest ros-industrial-consortium:hydro-devel changes. Look correct to you now?

**Comment by shaun-edwards** [comment]
Much better...happy reviewing @jrgnicho

**Comment by jrgnicho** [comment]
@psturgeon  I tested the new functionality and this is what I observed:
- Initial planning works properly
- Add functionality works only when a point is added relative to points in the original trajectory.  If a point is added relative to points added by the user, the getShortestPath(...) method only returns a subset of points
- Remove function work pretty well most of the time but it crashed on me once when I tried to removed a user added point
- Modify function crashes the application

In order to repeat these test, use the amos branch [integrate_descartes_path_planner](https://github.com/swri-robotics/amos/tree/issue_%2330_integrate_descartes_path_planner).  This branch generates the same test path each time the gui runs and reads ros parameters to control how many points the trajectory will contain.  Let me know if you need more details reproducing these tests.

**Comment by psturgeon** [comment]
@jrgnicho See the latest commits for testing. Add should be working correctly now. I'm working on a potential issue I saw in the remove function. Modify appears to be correct, however the UI isn't passing a valid cartesian UUID in right now.

**Comment by jrgnicho** [comment]
@psturgeon  My latest PR in amos should address the modify issue on the GUI side. I'll test your changes with this branch.

**Comment by psturgeon** [comment]
@jrgnicho Latest and greatest is pushed up here for testing. I believe the add, modify, and delete are all working correctly now. There are several debug logs that I've left in for the time being that I'll pull out after it gets put through the paces a little more.

**Comment by shaun-edwards** [comment]
@psturgeon, @jrgnicho Can this PR be approved?  Do things work "well enough"

**Comment by jrgnicho** [comment]
@shaun-edwards , I'm currently testing the latest changes and will provide feedback soon

**Comment by jrgnicho** [comment]
@psturgeon , after spending several minutes with it and trying every possible combination of edits that I could think of I just wasn't able to break it; it worked great.  +1 for merge to hydro-devel after code clean up.

**Comment by psturgeon** [comment]
@jrgnicho @shaun-edwards Comments are cleaned up and ready to go. There are still a few pieces of test code that are in there but commented out. I'm leaving them as reference for now or in case another issue comes up later that needs to be looked into - I'll plan on taking any of those out later.

**Comment by jrgnicho** [comment]
+1 for merge. @psturgeon  thanks for all the great work.

**Pull request merged**
