### PR TITLE
Trajectory ID changed to boost uuid

### PR DESCRIPTION
**Pull request by shaun-edwards**
This PR is a work in progress...not ready for review.

### CODE REVIEW

**Comment by shaun-edwards** [comment]
@psturgeon, this PR is in progress.  I'm having trouble getting the path planner to utilize non-integers for trajectory point IDs.  I've corrected the types where it was obvious, but one part seems to rely on ID's being an integer.

I've disable building of the path planner for now, but could you take a look?

Use the "You can also merge branches on the  command line." link above to find out how to pull my branch into your local repo.

**Comment by shaun-edwards** [comment]
@jrgnicho, this is good to go, please review.  @psturgeon updated the planning graph.  Everything builds and all (the few that there are) tests pass.

**Comment by shaun-edwards** [comment]
One more thing...this PR will break `amos`.

**Comment by jrgnicho** [comment]
I wanted to spot something wrong with it but I couldn't.  +1

**Comment by shaun-edwards** [comment]
Thanks @jrgnicho, I promise the next PR will be filled with issues.

**Pull request merged**
